# Generated by Django 3.1.7 on 2021-05-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210516_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_ar',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text_ar',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text_en',
        ),
    ]
