# Generated by Django 3.1.7 on 2021-06-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otp_totp', '0002_auto_20190420_0723'),
        ('otp_email', '0004_throttling'),
        ('otp_static', '0002_throttling'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDevices',
            fields=[
            ],
            options={
                'verbose_name': 'EmailDevice',
                'verbose_name_plural': 'EmailDevices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('otp_email.emaildevice',),
        ),
        migrations.CreateModel(
            name='StaticDevices',
            fields=[
            ],
            options={
                'verbose_name': 'StaticDevice',
                'verbose_name_plural': 'StaticDevices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('otp_static.staticdevice',),
        ),
        migrations.CreateModel(
            name='TOTPDevices',
            fields=[
            ],
            options={
                'verbose_name': 'TOTPDevice',
                'verbose_name_plural': 'TOTPDevices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('otp_totp.totpdevice',),
        ),
    ]
